### ISSUE TITLE
Option disable the toolbar?  

### ISSUE THREAD

**Issue by ddombrowsky** [deepak1556/pdf-viewer#8]
Is there any way to disable the toolbar at the top of the pdf-viewer page?  I know it seems backwards, but the way I'm using it, the title will never be accurate or even known, and the download link shouldn't be displayed.  Is there a way to do this?

**Comment by brenca** [comment]
You could use the `WebContents.executeJavascript` API in `electron` to run this code:
```javascript
document.querySelector('viewer-pdf-toolbar').style.display = "none"
document.querySelector('viewer-zoom-toolbar').style.display = "none"
```

**Comment by ddombrowsky** [comment]
I _knew_ there was a `WebContents` answer to this.  I just couldn't find it.  

Note that the function is `executeJavaScript` (capital S). https://github.com/electron/electron/blob/master/docs/api/web-contents.md#contentsexecutejavascriptcode-usergesture-callback

**Comment by ddombrowsky** [comment]
seems like this can be closed, since I don't think the PDF viewer even works anymore
